### ISSUE TITLE
"Watch LFE presentations" link is broken

### ISSUE THREAD

**Issue by adkelley** [lfe/docs#118]
http://docs.lfe.io/presentations.html -> http://docs.lfe.io/current/presentations.html

**Comment by prertik** [comment]
Every link if you try [http://docs.lfe.io/history.html](http://docs.lfe.io/history.html) is broken because it being migrated to [http://docs.lfe.io/current/history.html](http://docs.lfe.io/current/history.html). In fact when you go to [docs.lfe.io](docs.lfe.io), you are redirected to [http://docs.lfe.io/current/index.html](http://docs.lfe.io/current/index.html)

**Comment by wmealing** [comment]
I think this can be closed, as its now currently working.

**Comment by adkelley** [comment]
The new site http://docs.lfe.io/dev/  is now available
